// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK_67FN1eTXyD-uzL3oOclMO6GpKT827U',
    appId: '1:1009717812778:web:de2b1b1ef8a0ccbf70ed53',
    messagingSenderId: '1009717812778',
    projectId: 'mobileproject-414c0',
    authDomain: 'mobileproject-414c0.firebaseapp.com',
    storageBucket: 'mobileproject-414c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9__yZF7lJaxQedtgTfvKY4to-gRtNdZ8',
    appId: '1:1009717812778:android:0f5e852110a68e3470ed53',
    messagingSenderId: '1009717812778',
    projectId: 'mobileproject-414c0',
    storageBucket: 'mobileproject-414c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQHfyDFodX_O1rp8sknoZJ2MKPaM9kCOE',
    appId: '1:1009717812778:ios:afdbee063bec42e170ed53',
    messagingSenderId: '1009717812778',
    projectId: 'mobileproject-414c0',
    storageBucket: 'mobileproject-414c0.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQHfyDFodX_O1rp8sknoZJ2MKPaM9kCOE',
    appId: '1:1009717812778:ios:96b20a6c1788052270ed53',
    messagingSenderId: '1009717812778',
    projectId: 'mobileproject-414c0',
    storageBucket: 'mobileproject-414c0.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
